service: curiosity-lambda
provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: us-east-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    timeout: 10
    memorySize: 128
  renderPage:
    url: true
    handler: src/render.page
    timeout: 60
    memorySize: 1024
    environment:
      NASA_KEY: ${env.NASA_KEY}

