service: curiosity-lambda
provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: us-east-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    timeout: 10
    memorySize: 128

