service: curiosity-lambda
provider:
  name: aws
  runtime: nodejs18.x
  stage: production
  region: us-east-1
functions:
  updateRun:
    handler: src/update.run
    timeout: 10
    memorySize: 128
    environment:
      NASA_KEY: ${env:NASA_KEY}
      NASA_HOST: https://api.nasa.gov
  renderPage:
    url: true
    handler: src/render.page
    timeout: 60
    memorySize: 512
    environment:
      NASA_KEY: ${env:NASA_KEY}
      NASA_HOST: https://api.nasa.gov
    events:
      - cloudFront:
          eventType: render.page
          pathPattern: /*
          origin:
            OriginPath: /
